kind: secret
name: dockerconfigjson
get:
  path: dockerconfigjson
  name: .dockerconfigjson
---
kind: pipeline
type: kubernetes
name: chainflip-state-chain-pr

steps:
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<< pull_request >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Pull request check and build
#  - name: format-engine
#    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
#    commands:
#      - cargo fmt --all -- --check
  - name: check-state-chain
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_REDIS: "redis://redis-headless:6379/sccache"
    commands:
      - cargo check --release --bin state-chain-node
      - sccache -s
    resources:
      limits:
        cpu: 2000m
  - name: build-state-chain
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_REDIS: "redis://redis-headless:6379/sccache"
    commands:
      - cargo build --release --bin state-chain-node
      - sccache -s
    resources:
      limits:
        cpu: 2000m
  - name: test-state-chain
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_REDIS: "redis://redis-headless:6379/sccache"
    commands:
      - cargo test --release
      - sccache -s
    resources:
      limits:
        cpu: 2000m

# Config
trigger:
  event:
    - pull_request
  paths:
    - state-chain/**/*.rs

node_selector:
  type: "ci"

image_pull_secrets:
  - dockerconfigjson