{
	"data": "ENC[AES256_GCM,data:C5MSaCeKI1mqvE1upBVrz2L/9f7R9R4lstoTvH3xKlLW10CyrCx026xwnfJxR7hJwEaUUJSz6Lmoq8lIhcaBPc97wYEa1tyK+GUgMpHn3Hhc29FGgGqAwO9DNeeU2J7MJCUHYPcxqQ5+D7ORCrqe+NwNH2p5MtPV+zpQ6kZs5dS9jsKhaucyv3Z9qsjJP/pReSKbosTjjAPdrFF/466AhqGet3sB/WhNKg9Ts6XSbC3/kAbX23cTGfQy6QBjEBlmJmgy/0V6v9j10DNjYCl4ULO8wuZMyCAAFH76o+fcSMJhdAgxs2VPYXkD/SrbmcWZL6brcXBXtuQB8Wth14XWuLZ+HE+ERg2N897M3rEA7jmuvYJhjjZtnZ8ugTsNT1bwH+XiB2H3tH6r6ypAP3z25giMwnL70U2Zm1qRQI4JZFgtqqmV8AFooDGqUBAKwrHyXnebPT0jsrVAmgRvsH4lXN4cFAt20Fobzk7FcpN8Zj+9qC34t8Ymf2rsgX5k125esPII5Hglw34hvOYiLdXtWPC2ddPl3Dw8FW2cXKp2rgKnncxqXMorh3MMO20nY0f/kiJMSS8alnx2L7i6t74jFtxYmwgEcnbSywf4+B/Obb7LnHzDL3Yn9w76mNSURX+qOqMW1O5seR3zD4z9v3WMSrFLd2y4M4ELzJ5iSmirdvYYJLFCHfoN0Soqt8iXguCNSbxP5wC25oJI5Xs=,iv:qBqdRkcEg8vgFZ7I5HLbqW4CcNMPQk8xSox24BX9rDo=,tag:OUeE42nndFtygAM8lCowCw==,type:str]",
	"sops": {
		"kms": [
			{
				"arn": "arn:aws:kms:eu-central-1:951386877486:key/18dee810-875f-4db4-baaf-a28518d692b5",
				"created_at": "2021-12-02T14:03:08Z",
				"enc": "AQICAHhn0a7PfyeAXmu7V4t3mJBmTT5xv56Vw+0/XfwSCqtg5wFcWy62kVYMhGsE5+bzbIPkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSlzAmwStLRefOA4DAgEQgDuKcvRHGe+UN3p1AVyh6cZrGvzav0C9DG0tHq6tz+dkzrud+zm6eDGwis/Ym6iEAX/cdwV63Y9wG9+ocw==",
				"aws_profile": ""
			}
		],
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2021-12-13T15:46:23Z",
		"mac": "ENC[AES256_GCM,data:Hmg2NnIH9excCGRoPRBVPrIId0UizhpVKxAliFXCaEkn5+fFTpPN6NpZVNV/6QN4Vqx8XJDsyqqIvqara4Hx1vQ/vxDlgJA72Q6X/FlVa6yWCb/BWub2mMO8F/sJ1HXlHpOXOmEAEzvEMKw1BfZjHc+jLTbpbupwQKU5xbgHVG8=,iv:4n67DxAdOgwTKx3WfkEY0+Qa27fQ3qBX9t4IE4CxIFQ=,tag:t3cakcA8B6tKpimJcRSFJQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}