version: "3"

services:
  bashful-engine: &engine
    container_name: bashful-engine
    image: ${BASE_IMAGE_URL}chainflip-engine:${TAG}
    depends_on:
      - bashful-node
    environment:
      RUST_BACKTRACE: full
    volumes:
      - ./engine/config/testnet/bashful:/chainflip-engine/config

  bashful-node: &node
    container_name: bashful-node
    image: ${BASE_IMAGE_URL}state-chain-node:${TAG}
    ports:
      - "9944:9944"
      - "9933:9933"
    command:
      - --chain
      - test
      - --base-path
      - /state-chain-node/data/
      - --validator
      - --rpc-methods
      - Unsafe
      - --rpc-external
      - --ws-external
      - --rpc-cors
      - all

  doc-engine:
    <<: *engine
    container_name: doc-engine
    depends_on:
      - doc-node
    volumes:
      - ./engine/config/testnet/doc:/chainflip-engine/config

  doc-node:
    <<: *node
    ports:
      - "9934:9933"
    container_name: doc-node

  dopey-engine:
    <<: *engine
    container_name: dopey-engine
    depends_on:
      - dopey-node
    volumes:
      - ./engine/config/testnet/dopey:/chainflip-engine/config

  dopey-node:
    <<: *node
    ports:
      - "9935:9933"
    container_name: dopey-node

  grumpy-engine:
    <<: *engine
    container_name: grumpy-engine
    depends_on:
      - grumpy-node
    volumes:
      - ./engine/config/testnet/grumpy:/chainflip-engine/config

  grumpy-node:
    <<: *node
    ports:
      - "9936:9933"
    container_name: grumpy-node

  happy-engine:
    <<: *engine
    container_name: happy-engine
    depends_on:
      - happy-node
    volumes:
      - ./engine/config/testnet/happy:/chainflip-engine/config

  happy-node:
    <<: *node
    ports:
      - "9937:9933"
    container_name: happy-node

