kind: pipeline
type: docker
name: chainflip-engine-pr

steps:
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<< pull_request >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Pull request check and build
#  TODO: define formatting rules
#  - name: format-chainflip-engine
#    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
#    commands:
#      - cargo fmt --all -- --check
  - name: check-chainflip-engine
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_DIR: /cache
    commands:
      - cargo check --release --bin chainflip-engine
      - sccache -s
    volumes:
      - name: cache
        path: /cache
  - name: build-chainflip-engine
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_DIR: /cache
    commands:
      - cargo build --release --bin chainflip-engine
      - sccache -s
    volumes:
      - name: cache
        path: /cache
  - name: test-chainflip-engine
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    environment:
      SCCACHE_DIR: /cache
    commands:
      - cargo test --release
      - sccache -s
    volumes:
      - name: cache
        path: /cache


# Config
trigger:
  event:
    - pull_request
  paths:
    - engine/**/*.rs

node:
  builder: "true"
volumes:
  - name: cache
    host:
      path: /mnt/chainflip-build-runner/sccache
image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
type: docker
name: cfe-integration-tests

services:
  - image: trufflesuite/ganache-cli:latest
    name: ganache
    ports: [8545]
    command:
      - ganache-cli --mnemonic chainflip
  - image: nats:latest
    ports: [4222,8222]
    name: nats

steps:
  - name: run-tests
    image: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
    commands:
      - chmod +x ./engine/tests/scripts/setup.sh
      - ./engine/tests/scripts/setup.sh
      - cargo test -p chainflip-engine --test stake_manager_integration
    volumes:
      - name: cache
        path: /cache

# Config
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
volumes:
  - name: cache
    host:
      path: /mnt/chainflip-build-runner/sccache