[package]
name = "cf-p2p"
version = "0.1.0"
authors = ["Andy Bell <andy@chainflip.io>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
sp-runtime  = "3.0.0"
sc-network = "0.9.0"
log = "0.4.14"

[dev-dependencies]
async-std = "1.9.0"
