[package]
authors = ['Chainflip Team <https://github.com/chainflip-io>']
description = 'FRAME pallet for managing stakers of FLIP.'
edition = '2018'
homepage = 'https://chainflip.io'
license = '<TODO>'
name = 'pallet-cf-staking'
repository = 'https://github.com/chainflip-io/chainflip-backend'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0'

[dependencies]
# Internal deps
cf-traits = { path = '../../traits', default-features = false }
pallet-cf-validator = { path = '../cf-validator', default-features = false }

# Non-substrate external deps

# Substrate deps
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-io = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'cf-traits/std',
    'pallet-cf-validator/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
    'sp-std/std',
]
