# SnowWhite configurations for the CFE
# Used in integration tests, as this is the governance sudo user
# on the three-node-test chain spec

[state_chain]
# 32 byte hex secret key - associated with the node's public id (public key)
signing_key_file = "/Users/kaz/Documents/cf-dev-keys/bashful_key"
ws_endpoint = "ws://127.0.0.1:9944"

[eth]
from_block = 0
node_endpoint = "ws://localhost:8545"
# Ethereum private key file path. Default is the docker secrets path. This file should contain a hex-encoded private key.
private_key_file = "/Users/kaz/Documents/cf-dev-keys/eth_hh_acct_0_key"
# Address used on the Hardhat/Brownie tests
key_manager_eth_address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
stake_manager_eth_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

# not used by SnowWhite
[health_check]
hostname = "127.0.0.1"
port = 5555

# not used by SnowWhite
[signing]
db_file = "data.db"
