[package]
name = 'cf-session-benchmarking'
version = '0.1.0'
description = 'Chainflip session pallet benchmark'
authors = ['Chainflip Team <https://github.com/chainflip-io>']
homepage = 'https://chainflip.io'
edition = '2021'
license = '<TODO>'
publish = false
repository = 'https://github.com/chainflip-io/chainflip-backend'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
rand = { version = '0.7.2', default-features = false }

# Required for bechmarking
pallet-cf-validator = { path = '../pallets/cf-validator', default-features = false }
pallet-cf-staking = { path = '../pallets/cf-staking', default-features = false }
pallet-cf-reputation = { path = '../pallets/cf-reputation', default-features = false }
pallet-cf-vaults = { path = '../pallets/cf-vaults', default-features = false }
cf-traits = { path = '../traits', default-features = false }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.0.0'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '2.0.1'

[dependencies.pallet-authorship]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.sp-consensus-aura]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'
version = '0.10.0-dev'

[dependencies.pallet-session]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'
features = ['historical']

[dependencies.pallet-grandpa]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.sp-finality-grandpa]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'
# features = ["derive-codec"]

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.sp-application-crypto]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/chainflip-io/substrate.git'
tag = 'chainflip-monthly-2022-05'

[features]
default = ['std']
std = [
  'sp-std/std',
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'pallet-session/std',
  'sp-runtime/std',
  'sp-finality-grandpa/std',
]