on:
  workflow_call:
    inputs:
      network:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  create:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if the chainspec file already exists
        id: check-chainspec-exists
        continue-on-error: true
        run: |
          if [ -f state-chain/node/chainspecs/${{ inputs.network }}.chainspec.raw.json ]; then
            echo "Chainspec already exists, skipping"
            exit 1
          fi

      - name: Configure AWS credentials using OIDC
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::962042992619:role/chainflip-github-bot

      - name: Download binary artifacts
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: actions/download-artifact@v3
        with:
          name: chainflip-backend-bin-ubuntu-22.04

      - name: Setup python
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: actions/setup-python@v3

      - name: Create chainspec
        if: steps.check-chainspec-exists.outcome == 'success'
        run: |
          echo "DATE=$(date '+%d-%m-%Y')" >> $GITHUB_ENV
          python3 ./ci/scripts/create_chainspec.py ${{ inputs.network }} ./chainflip-node

      - uses: EndBug/add-and-commit@v9
        if: steps.check-chainspec-exists.outcome == 'success'
        with:
          default_author: github_actions
          add: state-chain/node/chainspecs/*.json
          message: "Create chainspec for ${{ inputs.network }}"
          new_branch: chainspec/${{ inputs.network }}-${{ env.DATE }}

      - name: Upload chainspec to s3
        if: steps.check-chainspec-exists.outcome == 'success'
        run: |
          aws s3 cp state-chain/node/chainspecs/${{ inputs.network }}.chainspec.raw.json s3://repo.chainflip.io/chainspecs/${{ inputs.network }}.chainspec.json

      - name: Set summary output
        if: steps.check-chainspec-exists.outcome == 'success'
        run: |
          echo "Chainspec created for `${{ inputs.network }}`" >> $GITHUB_STEP_SUMMARY

      - name: Set summary output
        if: steps.check-chainspec-exists.outcome == 'failure'
        run: |
          echo "No chainspec created for `${{ inputs.network }}`" >> $GITHUB_STEP_SUMMARY