on:
  workflow_call:
    inputs:
      network:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  actions: write
  pull-requests: write

jobs:
  create:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if the chainspec file already exists
        id: check-chainspec-exists
        continue-on-error: true
        run: |
          if [ -f state-chain/node/chainspecs/${{ inputs.network }}.chainspec.raw.json ]; then
            echo "Chainspec already exists, skipping"
            exit 1
          fi

      - name: Configure AWS credentials using OIDC
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::962042992619:role/chainflip-github-bot

      - name: Download binary artifacts
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: actions/download-artifact@v3
        with:
          name: chainflip-backend-bin-ubuntu-22.04

      - name: Setup python
        if: steps.check-chainspec-exists.outcome == 'success'
        uses: actions/setup-python@v3

      - name: Create chainspec
        if: steps.check-chainspec-exists.outcome == 'success'
        run: |
          echo "DATE=$(date '+%d-%m-%Y')" >> $GITHUB_ENV
          python3 ./ci/scripts/create_chainspec.py ${{ inputs.network }} ./chainflip-node

      - name: Create a pull request against current branch
        if: steps.check-chainspec-exists.outcome == 'success'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CF_GITHUB_BOT_TOKEN }}
          commit-message: "[skip ci] - Create chainspec for ${{ inputs.network }}"
          title: "New chainspec for ${{ inputs.network }}"
          body: |
            This PR was automatically created by the `create-chainspec` workflow.
            Please bear in mind this might not be the final chainspec.
            Only once the `${{ inputs.network }}.rs` file has been updated should this PR be merged.
            Successive pushes to the release branch will not create new PRs. 
            To recreate this chainspec, please first delete the chainspec files from the release branch.
          branch: chainspec/${{ inputs.network }}-${{ env.DATE }}
          committer: cf-bot <dev@chainflip.io>
          reviewers: |
            dandanlen
            tomjohnburton
            ahasna
            martin-chainflip
          add-paths: |
            state-chain/node/chainspecs/*.json

      - name: Set summary output
        if: steps.check-chainspec-exists.outcome == 'success'
        run: |
          echo "Chainspec created for `${{ inputs.network }}`" >> $GITHUB_STEP_SUMMARY
          echo "[Pull requests created](${{ steps.create-pr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY

      - name: Set DISCORD_URL
        run: |
          if [ "${{ inputs.network }}" == "perseverance" ]; then
            echo "DISCORD_URL=${{ secrets.CF_DISCORD_WH_NETWORK_PERSEVERANCE }}" >> $GITHUB_ENV
          else
            echo "DISCORD_URL=${{ secrets.CF_DISCORD_WH_NETWORK_SISYPHOS }}" >> $GITHUB_ENV
          fi

      - name: Notify that chainspec was created
        if: steps.check-chainspec-exists.outcome == 'success'
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_URL }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            ⛓️ New chainspec available for review
            > **Network:** ${{ inputs.network }}
            > **Pull requests:** ${{ steps.create-pr.outputs.pull-request-url }}

      - name: Upload chainspec to s3
        if: steps.check-chainspec-exists.outcome == 'failure'
        run: |
          aws s3 cp state-chain/node/chainspecs/${{ inputs.network }}.chainspec.raw.json s3://repo.chainflip.io/chainspecs/${{ inputs.network }}.chainspec.json

      - name: Set summary output
        if: steps.check-chainspec-exists.outcome == 'failure'
        run: |
          echo "No chainspec created for `${{ inputs.network }}`" >> $GITHUB_STEP_SUMMARY

      - name: Notify that chainspec was created
        if: steps.check-chainspec-exists.outcome == 'failure'
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_URL }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            ✅ Chainspec uploaded to S3
            > **Network:** ${{ inputs.network }}
            > **S3 URL:** https://repo.chainflip.io/chainspecs/${{ inputs.network }}.chainspec.json