# This CI runs a lot of the jobs in parallel to speed up development time. We also run a simpler suite of bouncer tests.
name: Release Chainflip Development
on:
  push
concurrency:
  group: ${{ github.ref }}-release-development
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_20_build.yml
    secrets: inherit
    with:
      network: development
      commit_hash: 0.7.3
