name: Release Chainflip Test
on:
  push:

concurrency:
  group: ${{ github.ref }}-release-sisyphos
  cancel-in-progress: true

jobs:
  chainspec:
    uses: ./.github/workflows/_60_create_chainspec.yml
    secrets: inherit
    with:
      network: test
