name: Release Chainflip TEST
on:
  push:

concurrency:
  group: ${{ github.ref }}-release-partnernet
  cancel-in-progress: true

jobs:
  chainspec:
    uses: ./.github/workflows/_60_create_chainspec.yml
    secrets: inherit
    with:
      network: sisyphos